"""
Django settings for zappy project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import mongoengine

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'vtn%+(x9w9r8rz4)g%nyvdpj956)0elffux#z5x-^f(4_g&&zz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['zappy.serveo.net', 'localhost', '127.0.0.1', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'slack.apps.SlackConfig',
    'twitter',
    'frontend',
    'rest_framework',
    'djcelery',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zappy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zappy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': ''
    }
}
_MONGODB_HOST = 'cluster0-8ovpy.mongodb.net'
_MONGODB_TEST_USER = 'test_user'
_MONGODB_TEST_PASSWD = 'c667QYLP4sIvqXoy'
_MONGODB_TEST_HOST = 'cluster0-8ovpy.mongodb.net'
_MONGODB_TEST_NAME = 'test'
_MONGODB_TEST_DATABASE_HOST = 'mongodb+srv://%s:%s@%s/%s' % (
    _MONGODB_TEST_USER, _MONGODB_TEST_PASSWD, _MONGODB_HOST, _MONGODB_TEST_NAME
)
mongoengine.connection.disconnect()
mongoengine.connect(_MONGODB_TEST_NAME, host=_MONGODB_TEST_DATABASE_HOST)

TEST_MONGO_DATABASE = {
    'db': _MONGODB_TEST_NAME,
    'host': [_MONGODB_TEST_HOST],
    'user': _MONGODB_TEST_USER,
    'password': _MONGODB_TEST_PASSWD,
    'port': 27017,
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# CELERY SETTINGS
BROKER_URL = 'redis://localhost:6379/0'
BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600 * 24}  # 24 hours. This avoids duplication.
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
# CELERY_RESULT_BACKEND = 'djcelery.backends.database:DatabaseBackend'
CELERYD_CONCURRENCY = 50
CELERY_SEND_EVENTS = True

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": 'redis://localhost:6379/1',
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# SLACK API Configurations
# ----------------------------------------------
SLACK_CLIENT_ID = ''
SLACK_CLIENT_SECRET = ''
SLACK_VERIFICATION_TOKEN = ''
SLACK_OATH_ACCESS_TOKEN = ''

# twitter api conf
TWITTER_CONSUMER_KEY = ""
TWITTER_CONSUMER_SECRET = ""
TWITTER_ACCESS_KEY = ""
TWITTER_ACCESS_SECRET = ""

TWITTER_ACCOUNT_ID = 'testuseraccoun5'
SLACK_SEARCH_KEYWORD = 'go'
